### ISSUE TITLE
add a suffix - add a new Markdown 

### ISSUE THREAD

**Issue by dinobib** [samwilson/dokuwiki-plugin-addnewpage#41]
Hi,
How could we force a .md suffix to ensure tech page would be  `title.md`and so that the markdownextra plugin will automatically parse it as markdown.
I haven’t find the way how I could automatically add the .md suffix. 
It would be also useful to have this option configurable by adding a parameter to the syntax. I think many markdownextra plugin user would like this option.
I search for a way the url to be `?do=edit&id=title.md` and not `?do=edit&id=title`but I’m just to dumb to figure out.
Thanks for your help.

**Comment by dinobib** [comment]
Ok,
I have found a way for my need.
````js
var id = ns.val()+":"+title.val();
		var id = id + ".md";
        jQuery(this).find("input[name='id']").val(id);
````

Maybe someone could improve this. I think it would be useful to check if the user have ever type .md. And other imprvovement, it will be a nice addition to have this as an option with a parameter.

**Comment by samwilson** [comment]
I think this should be done in the Markdown plugin because there are lots of other ways in which a user could create a page — it'd be better to guard all of them to ensure the `.md` suffix.

**Comment by samwilson** [comment]
(Sorry, didn't mean that to come across as so negative. Let me know if you disagree, and I"ll look at adding the option. Thanks!)
