### ISSUE TITLE
Button not showing

### ISSUE THREAD

**Issue by atlarep** [samwilson/dokuwiki-plugin-addnewpage#58]
I installed this plugin in order to make it easier for my users to create pages and assign them to a namespace easily, but the 'Add New Page' function/button doesn't show anywhere in my wiki, even as admin. Am I missing a step here?

This is how it looks in the conf settings page.
![image](https://cloud.githubusercontent.com/assets/20726009/17251030/0164e700-5575-11e6-9e2e-0f8ba43b58bb.png)

**Comment by samwilson** [comment]
Have you added the {{NEWPAGE}} syntax to a wiki page?

On 29 July 2016 10:13:24 pm AWST, atlarep <notifications@github.com> wrote:
>I installed this plugin in order to make it easier for my users to
>create pages and assign them to a namespace easily, but the 'Add New
>Page' function/button doesn't show anywhere in my wiki, even as admin.
>Am I missing a step here?
>
>This is how it looks in the conf settings page.
>![image](https://cloud.githubusercontent.com/assets/20726009/17251030/0164e700-5575-11e6-9e2e-0f8ba43b58bb.png)
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/samwilson/dokuwiki-plugin-addnewpage/issues/58

-- 
Sent from my field telephone with K-9 Mail. Please excuse brevity.

**Comment by atlarep** [comment]
No. Do You mean from the page editor?

**Comment by samwilson** [comment]
Yep! So, wherever you want the new-page form to appear, just put `{{NEWPAGE}}`. See https://www.dokuwiki.org/plugin:addnewpage for more information. You can also add to e.g. a sidebar if you want.

**Comment by atlarep** [comment]
I see, My apologies. Somehow I got the idea that after installing I would
see a button to add a new page no matter where i was in the wiki at a given
moment (i.e. Admin, start, etc).

Also, what interests me more is the ability to assign a page to an existing
namespace easily since my users are not very skilled on Dokuwiki.

**Comment by samwilson** [comment]
Ah, cool, yeah it can definitely do that too! :) Does your wiki have a sidebar or other global navigation element that it'd be appropriate to add the new-page form to?

**Comment by atlarep** [comment]
Yeah, I have the Navigation left panel and the tools panel underneath on
the left side of the page.
I am using the Vector template.

**Comment by samwilson** [comment]
Hm, I'm not familiar with that template, but if there's a page called `wiki:sidebar` or similar, you could try adding the new-page syntax to that. You might also need to put `~~NOCACHE~~` on it as well, so it'll work for people logged in or not.

**Comment by atlarep** [comment]
Thanks man. I'll give it a shot tomorrow and see what happens. Will respond
with the results.

**Comment by atlarep** [comment]
I just tried it and it works great. This is way easier than I thought.
Now I have to figure out how to add it to the toolbox or to every single page.

**Comment by atlarep** [comment]
BTW.- This is the template I am using.
https://github.com/arsava/dokuwiki-template-vector

I am trying to add your plugin to this toolbar:
![image](https://cloud.githubusercontent.com/assets/20726009/17299008/735c51e2-57da-11e6-99c3-1beb92c3a39f.png)

**Comment by samwilson** [comment]
If you can figure out where in that template to place it (I think maybe somewhere [here](https://github.com/arsava/dokuwiki-template-vector/blob/46d2a96232b18c059b36e96f6bd714c6628413d0/main.php#L720)) then you can use `tpl_include_page($pageid)` to stick the contents of a normal wikipage anywhere in a template.

There's more info about this on dokuwiki.org.

**Comment by atlarep** [comment]
Thanks for the info. I found that line on my main.php, but I am not sure what to add there without breaking it. 
Sorry, I am new to DokuWiki.

**Comment by atlarep** [comment]
I was thinking of putting it on the TABS (top right):
![image](https://cloud.githubusercontent.com/assets/20726009/17336322/add45ab4-58ab-11e6-8241-881aa8fda572.png)

I found the file where I can add it (/vector/user/tabs.php), but can't get the code right; here is an example:

```
//read tab
if(!empty($INFO["exists"])){
    //ATTENTION: "ca-view" is used as css id selector!
    $_vector_tabs_right["ca-view"]["text"] = $lang["vector_read"];
    if ($vector_context !== "discuss"){ //$vector_context was defined within main.php
        $_vector_tabs_right["ca-view"]["wiki"]  = ":".getID();
        if ($ACT === "show") { //$ACT comes from DokuWiki core
            $_vector_tabs_right["ca-view"]["class"] = "selected";
        }
    }else{
        $_vector_tabs_right["ca-view"]["wiki"]  = ":".substr(getID(), strlen(tpl_getConf("vector_discuss_ns"))-1);
    }
}

```
Any suggestions? Thanks in advance.

**Comment by samwilson** [comment]
Did you copy `user/tabs.php.dist` to create your `user/tabs.php`? That seems to have lots of examples in it.

But anyway, I'm not sure if I'm on the right track (haven't got time to get it all up and running locally this morning), but I'm thinking that you could create a page e.g. `wiki:new-page-form` that contains only `{{NEWPAGE}}` (configured however you want), and then add it to the right tabs with the following in `user/tabs.php`:

```php
$_vector_tabs_right['newpage'] = tpl_include_page('wiki:new-page-form', false);
```

See, I think [here](https://github.com/arsava/dokuwiki-template-vector/blob/46d2a96232b18c059b36e96f6bd714c6628413d0/main.php#L197) any element of this `$_vector_tabs_right` array that *isn't* an array will just be passed through and echoed at the [end](https://github.com/arsava/dokuwiki-template-vector/blob/46d2a96232b18c059b36e96f6bd714c6628413d0/main.php#L237) of that function.

**Comment by atlarep** [comment]
I didn't get to see the examples there. I'll check in the morning. I got
sidetracked because the navigation panel is only showing a limited amount
of items for some reason.
I did create the new-page-form, but kept getting errors with the tab.
I'll try what you suggested again.

Thanks

**Comment by atlarep** [comment]
Looks like this did the trick on /user/tabs.php:
`//Create New Page Tab
$_vector_tabs_right["tab-newpage"]["text"] = "Add New Page";
$_vector_tabs_right["tab-newpage"]["wiki"] = ":Add_New_Page";`

![image](https://cloud.githubusercontent.com/assets/20726009/17370593/a18146cc-596a-11e6-8918-31b3dc74aaa4.png)


Thank you so much!!!

**Comment by samwilson** [comment]
Oh cool! Well done. :)

Glad it's working properly.

**Comment by atlarep** [comment]
Thanks so much for your help.
Now i just have to figure out the auth:ad groups properly so i can release
it to my users.

**Comment by samwilson** [comment]
ah, yes, I remember struggling with that stuff a couple of years ago (I used to be an admin for a Dokuwiki company intranet). It does work! In the end... :-)

**Comment by atlarep** [comment]
I guess that's my job now. LOL
I actually got it to work fine for superuser and manager group. The problem
i am having is setting up authad for the simple/readonly users. Can't seem
to find anything on that part.
