### ISSUE TITLE
Slow loading since installation

### ISSUE THREAD

**Issue by ithurtswhenip** [samwilson/dokuwiki-plugin-addnewpage#89]
Hi,

Since the installation I have the problem that pages where I can select "Add page" take an incredibly long time to load. Pages without the option load in the expected time. As soon as I deactivate the plugin, all pages load again as I expect.

Since I took over the system from my predecessor, PHP 5.6 is still running on the server. But this should be changed soon. Could this be a problem?

Thanks in advance!

**Comment by eduardomozart** [comment]
After upgrading to PHP 8.1 and changing the template from "Argon Alternative" to "Read the Dokus", I also noticed the same issue. The following message is being shown at the sidebar:

```
Warning: Undefined array key 1 in /home/robertinho/public_html/wiki/lib/plugins/addnewpage/syntax.php on line 66
```

**Comment by ithurtswhenip** [comment]
Works for me as well!
Thanks!
